// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr31TlTVVWelBPDxNPqEy8fxotyx9vfLo',
    appId: '1:1019543970250:web:90adc2330f8bfc7a8a6f33',
    messagingSenderId: '1019543970250',
    projectId: 'safetrek-2b5a0',
    authDomain: 'safetrek-2b5a0.firebaseapp.com',
    storageBucket: 'safetrek-2b5a0.firebasestorage.app',
    measurementId: 'G-6MK6FPZDKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDogmOLJIpOOPuFA82V7IN8wxq97K5KRE',
    appId: '1:1019543970250:android:4c01f7d73024ee3b8a6f33',
    messagingSenderId: '1019543970250',
    projectId: 'safetrek-2b5a0',
    storageBucket: 'safetrek-2b5a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyM0QNJqqwwBvKHMzeZbmLEivMpukspa8',
    appId: '1:1019543970250:ios:ab30fcac1b4b58ce8a6f33',
    messagingSenderId: '1019543970250',
    projectId: 'safetrek-2b5a0',
    storageBucket: 'safetrek-2b5a0.firebasestorage.app',
    iosBundleId: 'com.example.safetrekProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyM0QNJqqwwBvKHMzeZbmLEivMpukspa8',
    appId: '1:1019543970250:ios:ab30fcac1b4b58ce8a6f33',
    messagingSenderId: '1019543970250',
    projectId: 'safetrek-2b5a0',
    storageBucket: 'safetrek-2b5a0.firebasestorage.app',
    iosBundleId: 'com.example.safetrekProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr31TlTVVWelBPDxNPqEy8fxotyx9vfLo',
    appId: '1:1019543970250:web:412b0c9f250def048a6f33',
    messagingSenderId: '1019543970250',
    projectId: 'safetrek-2b5a0',
    authDomain: 'safetrek-2b5a0.firebaseapp.com',
    storageBucket: 'safetrek-2b5a0.firebasestorage.app',
    measurementId: 'G-256QMFZ9CD',
  );
}
